// <auto-generated />
using System;
using FincialWebApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FincialWebApp1.Migrations
{
    [DbContext(typeof(FincialWebApp1Context))]
    [Migration("20230918080610_8i")]
    partial class _8i
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinancialWebApp1.Models.BankList", b =>
                {
                    b.Property<int>("BankListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankListId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BankListId");

                    b.ToTable("BankList");
                });

            modelBuilder.Entity("FinancialWebApp1.Models.MainClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BankListId")
                        .HasColumnType("int");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CTdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CTnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfAddingbyCutterEmployer")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfDelet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfEdit")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepotName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Import")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Ischecked")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LeftAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PreparationAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Stamps")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TheId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TransportationLoads")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WhoDelet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhoEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("cheackDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("cheackNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("checkDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateofTravel")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankListId");

                    b.ToTable("MainClass");
                });

            modelBuilder.Entity("FinancialWebApp1.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BankListId")
                        .HasColumnType("int");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CTdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CTnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CutAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CutAmountCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfAddingbyCutterEmployer")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfDelet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfEdit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateofDEpot")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepotName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormCuttingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Import")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Ischecked")
                        .HasColumnType("bit");

                    b.Property<string>("PreparationAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Stamps")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TransportationLoads")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WhoDelet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhoEdit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("cheackDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("cheackNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("checkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankListId");

                    b.ToTable("Trackers");
                });

            modelBuilder.Entity("FinancialWebApp1.Models.MainClass", b =>
                {
                    b.HasOne("FinancialWebApp1.Models.BankList", "BankList")
                        .WithMany()
                        .HasForeignKey("BankListId");

                    b.Navigation("BankList");
                });

            modelBuilder.Entity("FinancialWebApp1.Models.Track", b =>
                {
                    b.HasOne("FinancialWebApp1.Models.BankList", "BankList")
                        .WithMany()
                        .HasForeignKey("BankListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankList");
                });
#pragma warning restore 612, 618
        }
    }
}
